[tool.poetry]
name = "sport-activities-features-gui"
version = "0.1.0"
description = "GUI for sport-activities-features package"
authors = ["firefly-cpp <iztok@iztok-jr-fister.eu>"]

[tool.poetry.dependencies]
python = "^3.9"
sport-activities-features = "^0.3.7"
PyQt5 = "^5.15.7"
QtAwesome = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
